server:
  port: 31001
spring:
  freemarker:
    cache: false
    settings:
      template_update_delay: 0
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri:  mongodb://root:123@localhost:27017
      database: xc_cms


